/**
 * Pull the app's environment from AWS Secrets Manager into a local env file.
 *
 * Secrets (JSON key/value), one per stage:
 *   maatramtrust/dev/app   → .env.local
 *   maatramtrust/prod/app  → .env.production.local
 *
 * The pulled keys are validated against .env.example (the contract of what
 * the app needs) — missing/extra keys are reported by NAME only; secret
 * values are never printed. An existing target file is backed up to
 * `<file>.bak` before being overwritten.
 *
 * Run:  node scripts/pull-env.mjs [dev|prod]
 * Auth: uses the standard AWS credential chain — set AWS_PROFILE / AWS_REGION
 *       (or run `aws sso login`) as you would for the AWS CLI.
 */
import { readFileSync, writeFileSync, existsSync, copyFileSync } from "node:fs";
import {
  SecretsManagerClient,
  GetSecretValueCommand,
} from "@aws-sdk/client-secrets-manager";

const STAGES = {
  dev: { secretId: "maatramtrust/dev/app", file: ".env.local" },
  prod: { secretId: "maatramtrust/prod/app", file: ".env.production.local" },
};

const stage = process.argv[2] ?? "dev";
const target = STAGES[stage];
if (!target) {
  console.error(`Unknown stage "${stage}". Use: dev | prod`);
  process.exit(1);
}

/** Keys the app expects, straight from .env.example (single source of truth). */
function expectedKeys() {
  const example = readFileSync(
    new URL("../.env.example", import.meta.url),
    "utf8",
  );
  return example
    .split("\n")
    .map((line) => line.trim())
    .filter((line) => line && !line.startsWith("#") && line.includes("="))
    .map((line) => line.slice(0, line.indexOf("=")).trim());
}

/** KEY=value line, quoting values that would break .env parsing. */
function toEnvLine(key, value) {
  const text = String(value);
  if (/[\s#"'\\]/.test(text)) {
    return `${key}="${text.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, "\\n")}"`;
  }
  return `${key}=${text}`;
}

const client = new SecretsManagerClient({});

let secretString;
try {
  const result = await client.send(
    new GetSecretValueCommand({ SecretId: target.secretId }),
  );
  secretString = result.SecretString;
} catch (error) {
  console.error(
    `Could not read ${target.secretId}: ${error.name} — ${error.message}`,
  );
  console.error(
    "Check your AWS credentials (AWS_PROFILE / `aws sso login`) and region (AWS_REGION).",
  );
  process.exit(1);
}

let secrets;
try {
  secrets = JSON.parse(secretString);
} catch {
  console.error(
    `${target.secretId} is not valid JSON — expected key/value pairs.`,
  );
  process.exit(1);
}

const keys = Object.keys(secrets);
const expected = expectedKeys();
const missing = expected.filter((key) => !(key in secrets));
const extra = keys.filter((key) => !expected.includes(key));

const header = [
  `# Generated by scripts/pull-env.mjs from ${target.secretId}`,
  `# Pulled at ${new Date().toISOString()} — do not commit.`,
  "",
];
const body = keys
  .sort((a, b) => a.localeCompare(b))
  .map((key) => toEnvLine(key, secrets[key]));

if (existsSync(target.file)) {
  copyFileSync(target.file, `${target.file}.bak`);
  console.log(`Backed up existing ${target.file} → ${target.file}.bak`);
}
writeFileSync(target.file, `${header.join("\n")}${body.join("\n")}\n`);

console.log(
  `Wrote ${keys.length} keys from ${target.secretId} to ${target.file}`,
);
if (missing.length > 0) {
  console.warn(
    `⚠ Missing vs .env.example (add them to the secret): ${missing.join(", ")}`,
  );
}
if (extra.length > 0) {
  console.log(`ℹ Extra keys not in .env.example: ${extra.join(", ")}`);
}
if (missing.length === 0) {
  console.log("✓ All keys from .env.example are present.");
}
